DATABASE_URL = "postgresql://postgres:FitCom_1804@db.orouggcyiduqzkrrfica.supabase.co:5432/postgres"
SUPABASE_URL = "https://orouggcyiduqzkrrfica.supabase.co"
SUPABASE_KEY = "sb_publishable_yde1U4fI6j7SlWjLNWeSFw_b0TRsrDc"